apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: final
type: Opaque
data:
  secret: WldVeE9ERmxaVFk0WVRJeE9EQXpNMlExT0RabFpXVmhNemMyTURBNE1ERmlOV0l6Tm1JNVl6Y3pPV1ExWkRZd1pUZzBZemN6TjJGbFlqQmpNRFJoTm1SaU9ESXdOV1E0TVRjMVpUTTRNVFF4TldRME9EaG1Nemt6T1Rrd05qUXpZbUU0TWc9PQ==
